'use client';

import { Suspense, useState } from 'react';
import { Printer } from 'lucide-react';
import { REPORTS, reportsService } from '@/services';
import type { CellFormat, ReportCode, ReportRow } from '@/services/reportsService';
import { useData } from '@/services/useData';
import { addDays, startOfMonth, todayLagos } from '@/lib/dates';
import { formatCount, formatDate, formatDateTime, formatDuration, formatNaira } from '@/lib/format';
import { downloadFile, toCsv } from '@/lib/csv';
import { BarChartCard, LineChartCard } from '@/components/charts/Charts';
import {
  Button,
  Card,
  CardBody,
  DateInput,
  EmptyState,
  ErrorState,
  Field,
  InlineAlert,
  KpiGrid,
  KpiTile,
  PageHeader,
  Segmented,
  Select,
  SkeletonRows,
  cn,
  toastError,
} from '@/components/ui';

const RANGES = [
  { key: 'today', label: 'Today' },
  { key: 'week', label: 'Last 7 days' },
  { key: 'month', label: 'This month' },
  { key: 'custom', label: 'Custom' },
] as const;

function cell(v: ReportRow[string], format: CellFormat): string {
  if (v === null || v === undefined || v === '') return '—';
  switch (format) {
    case 'money':
      return formatNaira(String(v));
    case 'count':
      return formatCount(Number(v));
    case 'date':
      return formatDate(String(v));
    case 'datetime':
      return formatDateTime(String(v));
    case 'pct':
      return `${v}%`;
    case 'duration':
      return formatDuration(Number(v));
    default:
      return String(v);
  }
}

function ReportsView() {
  const today = todayLagos();
  const [code, setCode] = useState<ReportCode>('POSITION');
  const [range, setRange] = useState<(typeof RANGES)[number]['key']>('month');
  const [from, setFrom] = useState(startOfMonth(today));
  const [to, setTo] = useState(today);
  const meta = REPORTS.find((r) => r.code === code)!;

  const period =
    range === 'today'
      ? { from: today, to: today }
      : range === 'week'
        ? { from: addDays(today, -6), to: today }
        : range === 'month'
          ? { from: startOfMonth(today), to: today }
          : { from, to };

  const q = useData(() => reportsService.run(code, period), [code, period.from, period.to]);
  const r = q.data;

  const exportCsv = () => {
    if (!r) return;
    try {
      downloadFile(
        `${code.toLowerCase()}-${period.from}-to-${period.to}.csv`,
        toCsv(
          [...r.rows, ...(r.totals ? [r.totals] : [])],
          r.columns.map((c) => ({
            header: c.label,
            value: (row: ReportRow) => (row[c.key] ?? '') as string | number,
          }))
        )
      );
    } catch (e) {
      toastError(e);
    }
  };

  const exportExcel = () => {
    if (!r) return;
    // Excel opens an HTML table saved as .xls; figures keep their exact values.
    const head = `<tr>${r.columns.map((c) => `<th>${c.label}</th>`).join('')}</tr>`;
    const body = [...r.rows, ...(r.totals ? [r.totals] : [])]
      .map((row) => `<tr>${r.columns.map((c) => `<td>${row[c.key] ?? ''}</td>`).join('')}</tr>`)
      .join('');
    const html = `<html><head><meta charset="utf-8"></head><body><h3>${r.title}</h3><p>${period.from} to ${period.to} · generated by ${r.generatedBy}</p><table border="1">${head}${body}</table></body></html>`;
    downloadFile(
      `${code.toLowerCase()}-${period.from}-to-${period.to}.xls`,
      html,
      'application/vnd.ms-excel'
    );
  };

  return (
    <>
      <PageHeader
        title="Reports"
        description="Figures reconcile with the transaction and investment registers."
        actions={
          <>
            <Button size="sm" onClick={exportCsv} disabled={!r?.rows.length}>
              Export CSV
            </Button>
            <Button size="sm" onClick={exportExcel} disabled={!r?.rows.length}>
              Export Excel
            </Button>
            <Button size="sm" icon={Printer} onClick={() => window.print()} disabled={!r}>
              Print
            </Button>
          </>
        }
      />

      <Card className="mb-5 print:hidden">
        <CardBody className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Field label="Report" className="sm:col-span-2">
            <Select
              value={code}
              onChange={(e) => setCode(e.target.value as ReportCode)}
              options={REPORTS.map((x) => ({ value: x.code, label: x.title }))}
            />
          </Field>
          <div className={cn('sm:col-span-2', !meta.usesRange && 'opacity-50')}>
            <p className="mb-1 text-[13px] font-medium text-muted">Period</p>
            <Segmented
              label="Period"
              value={range}
              onChange={(v) => setRange(v)}
              options={RANGES.map((x) => ({ value: x.key, label: x.label }))}
            />
          </div>
          {range === 'custom' ? (
            <>
              <Field label="From">
                <DateInput value={from} onChange={(e) => setFrom(e.target.value)} />
              </Field>
              <Field label="To">
                <DateInput value={to} onChange={(e) => setTo(e.target.value)} />
              </Field>
            </>
          ) : null}
        </CardBody>
      </Card>

      {q.error ? (
        <ErrorState error={q.error} onRetry={q.reload} />
      ) : !r ? (
        <SkeletonRows rows={8} />
      ) : (
        <div className="space-y-5">
          <div>
            <h2 className="text-[17px] font-semibold">{r.title}</h2>
            <p className="text-[13px] text-muted">
              {meta.description}
              {r.range ? ` · ${formatDate(r.range.from)} to ${formatDate(r.range.to)}` : ''}
            </p>
            <p className="num text-xs text-muted">
              Generated by {r.generatedBy} on {formatDateTime(r.generatedAt)}
            </p>
          </div>

          {r.summary.length ? (
            <KpiGrid>
              {r.summary.map((s) => (
                <KpiTile
                  key={s.label}
                  label={s.label}
                  value={s.value}
                  kind={s.format === 'money' ? 'money' : s.format === 'count' ? 'count' : 'text'}
                />
              ))}
            </KpiGrid>
          ) : null}

          {r.chart ? (
            <Card>
              <CardBody>
                {r.chart.type === 'line' ? (
                  <LineChartCard
                    data={r.chart.data.map((d) => ({
                      label: String(d[r.chart!.xKey]),
                      value: Number(d[r.chart!.series[0].key]),
                    }))}
                    money={r.columns.some((c) => c.format === 'money')}
                  />
                ) : (
                  <BarChartCard
                    data={r.chart.data.map((d) => ({
                      label: String(d[r.chart!.xKey]),
                      value: Number(d[r.chart!.series[0].key]),
                    }))}
                    money={
                      r.chart.series[0].label.toLowerCase().includes('minute')
                        ? false
                        : r.columns.some((c) => c.format === 'money')
                    }
                  />
                )}
              </CardBody>
            </Card>
          ) : null}

          <Card>
            {r.rows.length ? (
              <div className="overflow-x-auto scrollbar-thin">
                <table className="w-full min-w-[640px] text-sm">
                  <caption className="sr-only">{r.title}</caption>
                  <thead>
                    <tr>
                      {r.columns.map((c) => (
                        <th
                          key={c.key}
                          scope="col"
                          className={cn(
                            'whitespace-nowrap border-b border-border bg-surface-2 px-3 py-2 text-xs font-semibold text-muted',
                            c.format === 'money' || c.format === 'count'
                              ? 'text-right'
                              : 'text-left'
                          )}
                        >
                          {c.label}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {r.rows.map((row, i) => (
                      <tr key={i}>
                        {r.columns.map((c) => (
                          <td
                            key={c.key}
                            className={cn(
                              'border-b border-border px-3 py-2',
                              c.format === 'money' || c.format === 'count' ? 'num text-right' : ''
                            )}
                          >
                            {cell(row[c.key], c.format)}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                  {r.totals ? (
                    <tfoot>
                      <tr className="font-semibold">
                        {r.columns.map((c) => (
                          <td
                            key={c.key}
                            className={cn(
                              'border-t-2 border-border-strong px-3 py-2',
                              c.format === 'money' || c.format === 'count' ? 'num text-right' : ''
                            )}
                          >
                            {r.totals![c.key] === undefined ? '' : cell(r.totals![c.key], c.format)}
                          </td>
                        ))}
                      </tr>
                    </tfoot>
                  ) : null}
                </table>
              </div>
            ) : (
              <EmptyState title="Nothing in this period" description="Choose a wider date range." />
            )}
          </Card>

          {r.notes.length ? (
            <InlineAlert tone="info" title="Notes">
              <ul className="list-disc pl-4">
                {r.notes.slice(0, 12).map((n) => (
                  <li key={n}>{n}</li>
                ))}
              </ul>
            </InlineAlert>
          ) : null}
        </div>
      )}
    </>
  );
}

export default function ReportsPage() {
  return (
    <Suspense>
      <ReportsView />
    </Suspense>
  );
}
