import type { Signatory } from '@/domain/types';
import { Badge } from '@/components/ui';

/** Specimen signature on file (SVG generated by the system, shown as an image). */
export function SpecimenCard({ s }: { s: Signatory }) {
  return (
    <figure className="rounded-md border border-border bg-white p-2 dark:bg-zinc-100">
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(s.specimenSvg)}`}
        alt={`Specimen signature of ${s.fullName}`}
        className="h-16 w-full object-contain"
      />
      <figcaption className="mt-1 flex items-center justify-between gap-2 text-xs text-zinc-700">
        <span className="truncate">{s.fullName}</span>
        <Badge tone={s.active ? 'neutral' : 'danger'}>
          Class {s.signClass}
          {s.active ? '' : ' · inactive'}
        </Badge>
      </figcaption>
    </figure>
  );
}

/** Uploaded instruction scan (image or PDF data URL). */
export function DocumentPreview({ name, data }: { name: string | null; data: string | null }) {
  if (!data) {
    return (
      <div className="flex h-40 items-center justify-center rounded-md border border-dashed border-border-strong text-center text-[13px] text-muted">
        {name ? `${name} (recorded, no scan attached)` : 'No scan attached'}
      </div>
    );
  }
  if (data.startsWith('data:application/pdf')) {
    return (
      <object
        data={data}
        type="application/pdf"
        aria-label={name ?? 'Instruction'}
        className="h-80 w-full rounded-md border border-border"
      />
    );
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={data}
      alt={name ?? 'Instruction scan'}
      className="max-h-96 w-full rounded-md border border-border object-contain"
    />
  );
}
